spring:
  application:
    name: ad-eureka

server:
  port: 8000

eureka:
  instance:
    hostname: localhost
  client:
    fetch-registry: false # 不从注册中心获取信息
    register-with-eureka: false # 不向注册中心注册自己
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

---  # 分隔符 in yml
spring:
  applciation:
    name: ad-eureka
  profiles: server1
server:
  port: 8001
eureka:
  instance:
    hostname: server1
    prefer-ip-address: false
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://server2:8002/eureka/,http://server3:8003/eureka/



---  # 分隔符 in yml
spring:
  applciation:
    name: ad-eureka
  profiles: server2
server:
  port: 8002
eureka:
  instance:
    hostname: server2
    prefer-ip-address: false
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://server1:8001/eureka/,http://server3:8003/eureka/


---  # 分隔符 in yml
spring:
  applciation:
    name: ad-eureka
  profiles: server3
server:
  port: 8003
eureka:
  instance:
    hostname: server3
    prefer-ip-address: false
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://server1:8001/eureka/,http://server2:8002/eureka/